mixin () {
  public query func getApiDoc() : async Text {
    "# UdyamAI Backend API\n"
    # "\n"
    # "## Purpose\n"
    # "UdyamAI is a market-analysis and financial-planning assistant for rural Indian entrepreneurs. The backend stores completed market analyses, a database of government schemes (with their rules and loan products), and answers contextual questions about them. It performs no live external data lookups: every analysis figure is a derived estimate computed from the user's inputs (village, block, district, state, business category, and capital) and the selected radius (5 km or 10 km). All financial calculations are deterministic backend code; the LLM chat layer may explain results but never computes or overrides any financial number. When external data is unavailable the frontend labels results as DEMO DATA; the backend never fabricates real-world figures.\n"
    # "\n"
    # "## Public methods\n"
    # "\n"
    # "### Analysis methods\n"
    # "\n"
    # "### runAnalysis(input, radius) : async AnalysisResult\n"
    # "Runs a complete analysis for the given input and radius, stores the result, and returns the derived result. `input` is `{ village, block, district, state, category, capital }`; `capital` is a `Nat` in Indian Rupees. `radius` is the variant `#R5km` or `#R10km`. The stored record is assigned a monotonically increasing `id` and a `createdAt` timestamp (nanoseconds since the Unix epoch, UTC). The result contains market reach, map data, four score cards, pricing, SWOT, and a six-category risk assessment. Every estimate carries a `provenance` label (`#Estimated`, `#Observed`, `#Calculated`, `#UserProvided`) and a `confidence` badge (`#High`, `#Medium`, `#Low`).\n"
    # "\n"
    # "### getAnalysis(id) : async ?Analysis\n"
    # "Returns the stored analysis with the given `id`, or `null` if none exists. `id` is the `Nat` assigned by `runAnalysis`.\n"
    # "\n"
    # "### listAnalyses() : async [Analysis]\n"
    # "Returns all stored analyses in insertion order.\n"
    # "\n"
    # "### chat(request) : async ChatResponse\n"
    # "Answers an Ask UdyamAI question in the context of an analysis. `request` is `{ analysisId, message, history }`, where `history` is an array of `{ role : { #user; #assistant }; content : Text }` messages. The assistant is strictly an explanation and recommendation layer: it never invents loan amounts, scheme eligibility, competitor numbers, financial calculations, or factual market values. If the context does not contain a number or fact the user asks for, it says so rather than guessing. If `analysisId` does not match a stored analysis, the assistant is told no analysis context is available.\n"
    # "\n"
    # "### Finance methods\n"
    # "\n"
    # "### computeFinancialPlan(input, rule) : async FinancialPlan\n"
    # "Computes the complete deterministic financial plan from `input` and a scheme-specific `rule`. `input` is `{ ownCapital, marginPercent, proposedProjectCost, loanRequirement, interestRatePercent, tenureMonths, moratoriumMonths, operatingCosts, workingCapital }`; `rule` is `{ name, beneficiaryContributionPercent, loanPercent, minProjectCost, maxProjectCost, interestRatePercent, tenureMonths, moratoriumMonths }`. The returned plan combines financing, amortization, moratorium, monthly operating cost, working capital, break-even, and cash requirement. All monetary values are `Nat` in Indian Rupees; percentages are `Nat` (whole percent). The plan is computed entirely by deterministic backend code.\n"
    # "\n"
    # "### computeFinancing(input, rule) : async Financing\n"
    # "Computes just the financing structure: feasible project cost, beneficiary contribution, maximum loan, and loan amount. The feasible project cost is what own capital supports at the margin, capped by the proposed cost and the scheme's maximum project cost. The loan percentage comes from the scheme-specific `rule` — never a universal 10/90 split.\n"
    # "\n"
    # "### computeAmortization(loanAmount, interestRatePercent, tenureMonths, moratoriumMonths) : async Amortization\n"
    # "Computes the EMI, total interest, total repayment, and the full repayment schedule using deterministic reducing-balance amortization. `interestRatePercent` is an annual percentage (`Nat`); `tenureMonths` and `moratoriumMonths` are months. During moratorium months no payment is made but interest accrues on the loan and is added to the amount repaid. The schedule has one row per month with `month`, `openingBalance`, `principal`, `interest`, `emi`, and `closingBalance` (all `Nat` in Rupees).\n"
    # "\n"
    # "### computeMoratorium(loanAmount, interestRatePercent, moratoriumMonths) : async Moratorium\n"
    # "Computes moratorium handling: the interest accrued during the moratorium, the repayment start month (`moratoriumMonths + 1`), and a plain-language explanation. During the approved moratorium period the borrower may not have to start regular repayment immediately, but interest still accrues and is added to the amount repaid.\n"
    # "\n"
    # "### computeWorkingCapital(input) : async WorkingCapital\n"
    # "Computes the working capital requirement split into initial requirement, monthly requirement, and emergency/buffer requirement. `input` is `{ initialRequirement, monthlyRequirement, emergencyBufferPercent }`; the buffer is `monthlyRequirement * emergencyBufferPercent / 100` and the total is the sum of the three components.\n"
    # "\n"
    # "### computeBreakEven(fixedCosts, variableCostPerUnit, pricePerUnit) : async BreakEven\n"
    # "Computes break-even sales and break-even units (where applicable). If `pricePerUnit` exceeds `variableCostPerUnit`, units are `ceil(fixedCosts / (pricePerUnit - variableCostPerUnit))` and sales are `units * pricePerUnit`; otherwise break-even is reported as not applicable (`breakEvenUnits = null`, sales `0`) with an explanation. All values are `Nat` in Rupees.\n"
    # "\n"
    # "### computeCashRequirement(feasibleProjectCost, workingCapitalTotal, buffer) : async CashRequirement\n"
    # "Computes the total cash requirement as the sum of the feasible project cost, working capital total, and buffer.\n"
    # "\n"
    # "### Scheme methods\n"
    # "\n"
    # "### listSchemes() : async [Scheme]\n"
    # "Returns all schemes in the government scheme database. Each `Scheme` carries `id`, `name`, `eligibility`, `projectCostRange` (`{ min; max }`, `max = 0` meaning no upper bound), `beneficiaryType`, optional scheme-specific `marginRequirement`, `loanPercentage`, `interestRate`, `tenureMonths`, `moratoriumMonths`, `documents`, `officialSource`, `lastVerifiedDate`, and `status` (`#Active`, `#Inactive`, `#UnderReview`). Optional values are only surfaced when verified in the database.\n"
    # "\n"
    # "### getScheme(id) : async ?Scheme\n"
    # "Returns the scheme with the given `id`, or `null` if none exists.\n"
    # "\n"
    # "### routeSchemes(input) : async SchemeRoutingResult\n"
    # "Deterministically routes potentially applicable schemes from `input` = `{ businessCategory, projectCost, location, beneficiaryCategory, contribution }`. Routing is a deterministic rule engine over the scheme database — no LLM involvement. A scheme matches when it is `#Active`, its project cost range contains the input project cost, and a `scheme_rules` entry for it matches the business category, location, and beneficiary category (case-insensitive). The result `heading` is always `\"Potentially applicable\"` — the backend never claims guaranteed eligibility. Each match shows why the scheme may fit, the project cost limit, contribution and loan (computed from verified margin/loan percentages), interest, tenure, moratorium, required documents, and an official verification note.\n"
    # "\n"
    # "### OQL: schema() and execute()\n"
    # "Stored data is queryable through the Object Query Layer. `schema()` returns the queryable schema; `execute(jsonQuery)` runs a JSON query. All entities are controller-only: only the platform controller (the Data Intelligence agent) can read rows through OQL; end users do not read them directly. The exposed entities are:\n"
    # "- `analysis` — columns `id`, `village`, `block`, `district`, `state`, `category`, `capital`, `radius` (`\"5km\"` or `\"10km\"`), `createdAt`, `demandScore`, `competitionLevel`.\n"
    # "- `scheme` — columns `id`, `name`, `eligibility`, `minProjectCost`, `maxProjectCost`, `beneficiaryType`, `marginRequirement`, `loanPercentage`, `interestRate`, `tenureMonths`, `moratoriumMonths`, `documents` (comma-joined), `officialSource`, `lastVerifiedDate`, `status` (`\"active\"`, `\"inactive\"`, `\"underReview\"`). Optional numeric columns use `0` / `0.0` as the sentinel for absent values.\n"
    # "- `schemeRule` — columns `schemeId`, `businessCategories`, `locations`, `beneficiaryCategories` (each comma-joined).\n"
    # "- `loanProduct` — columns `id`, `schemeId`, `name`, `interestRate`, `tenureMonths`, `moratoriumMonths`, `loanPercentage`, `marginRequirement` (optional numerics use `0` / `0.0` sentinels).\n"
    # "\n"
    # "### Authorization methods\n"
    # "- `_internet_identity_sign_in_start() : async Blob` — begins an Internet Identity sign-in and returns a challenge blob.\n"
    # "- `_internet_identity_sign_in_finish() : async Result<(), Error>` — completes sign-in and registers the caller.\n"
    # "- `_initialize_access_control() : async ()` — registers the caller as a user; the first caller to register becomes admin.\n"
    # "- `getCallerUserRole() : async UserRole` — returns the caller's role (`#admin`, `#user`, or `#guest`).\n"
    # "- `assignCallerUserRole(user, role) : async ()` — admin-only; assigns a role to a user.\n"
    # "- `isCallerAdmin() : async Bool` — whether the caller is admin.\n"
    # "\n"
    # "## Authentication and authorization\n"
    # "The app uses Internet Identity. Anonymous callers are treated as guests. Registration happens only when a caller signs in through the app's own frontend, which calls `_initialize_access_control` once as a signed-in caller before any role-guarded call. The first caller to register becomes admin; every subsequent caller becomes a user. A principal that never signed in through the frontend is unregistered even when it belongs to the app's owner, and a signed-in caller derived against a different origin is a different principal than the one the frontend registered.\n"
    # "\n"
    # "The app's frontend pins an Internet Identity derivation origin, published at `/.well-known/ii-derivation-origin` when available. An agent already holding the user's Internet Identity authorization derives the correct per-app principal against that origin (for example `icp identity link web <name> --app <host>`). Such a delegation acts with the user's full authority in this app until it expires.\n"
    # "\n"
    # "The finance and scheme methods are `query` functions that perform no state mutation and read no per-user data; they are callable by any signed-in caller. The OQL `schema()` and `execute()` methods are controller-only.\n"
    # "\n"
    # "## Units and encodings\n"
    # "- `capital`, prices, loan amounts, EMIs, and all monetary values are `Nat` in Indian Rupees (Rs).\n"
    # "- Percentages (`marginPercent`, `loanPercent`, `beneficiaryContributionPercent`, `interestRatePercent`) are `Nat` whole percent; `interestRate` on a `Scheme`/`LoanProduct` is `?Float` annual percentage.\n"
    # "- Tenure and moratorium are in months (`Nat`).\n"
    # "- `createdAt` and `lastVerifiedDate` are `Int` in nanoseconds since the Unix epoch (UTC).\n"
    # "- `radius` is the variant `#R5km` or `#R10km`; in OQL it is projected as the text `\"5km\"` or `\"10km\"`.\n"
    # "- `Provenance` and `Confidence` are variants; `RiskLevel` is `#Low`, `#Medium`, or `#High`.\n"
    # "- Distances in map data are `Float` kilometres; coordinates are `Float` latitude/longitude.\n"
    # "- In OQL, absent optional numeric scheme fields are projected as the sentinel `0` / `0.0`, and `status` as `\"active\"`, `\"inactive\"`, or `\"underReview\"`.\n"
    # "\n"
    # "## Lifecycle and polling\n"
    # "`runAnalysis` is synchronous: it computes and stores the result in one call and returns it directly. There is no background job and nothing to poll. `getAnalysis`, `listAnalyses`, and all finance and scheme methods read the stored state at call time and are synchronous queries.\n"
    # "\n"
    # "## Mutation retry safety\n"
    # "`runAnalysis` is not idempotent: each successful call appends a new analysis with a fresh `id`. Retrying a call that already succeeded creates a duplicate analysis. `chat` performs no state mutation and is safe to retry. `assignCallerUserRole` and `_initialize_access_control` are idempotent role assignments. All finance and scheme methods are read-only queries and safe to retry.\n"
    # "\n"
    # "## Errors, traps, limits, and gotchas\n"
    # "- `getAnalysis` and `getScheme` return `null` for an unknown `id`; they do not trap.\n"
    # "- `chat` traps if the inference service returns no choices or no text content.\n"
    # "- The assistant never invents financial figures, scheme eligibility, competitor numbers, or market values; it only explains the analysis context and uses backend-computed numbers.\n"
    # "- Financial calculations are deterministic backend code; the LLM never computes or overrides any financial number.\n"
    # "- Scheme routing is deterministic and never claims guaranteed eligibility — the result heading is always `\"Potentially applicable\"`.\n"
    # "- OQL `schema()` and `execute()` are controller-only; a non-controller caller receives no rows.\n"
    # "- Analysis figures are derived estimates, not observed market data. When external data is unavailable the frontend labels results as DEMO DATA; the backend does not fabricate real-world figures.\n";
  };
};
