/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
});
export const ChatRequest = IDL.Record({
  'history' : IDL.Vec(ChatMessage),
  'analysisId' : IDL.Nat,
  'message' : IDL.Text,
});
export const ChatResponse = IDL.Record({ 'reply' : IDL.Text });
export const Provenance = IDL.Variant({
  'Estimated' : IDL.Null,
  'UserProvided' : IDL.Null,
  'Calculated' : IDL.Null,
  'Observed' : IDL.Null,
});
export const Confidence = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Estimate = IDL.Record({
  'provenance' : Provenance,
  'value' : IDL.Nat,
  'confidence' : Confidence,
});
export const RepaymentRow = IDL.Record({
  'emi' : IDL.Nat,
  'month' : IDL.Nat,
  'principal' : IDL.Nat,
  'interest' : IDL.Nat,
  'closingBalance' : IDL.Nat,
  'openingBalance' : IDL.Nat,
});
export const PrincipalInterest = IDL.Record({
  'totalRepayment' : IDL.Nat,
  'totalInterest' : IDL.Nat,
  'totalPrincipal' : IDL.Nat,
});
export const Amortization = IDL.Record({
  'emi' : Estimate,
  'totalRepayment' : Estimate,
  'totalInterest' : Estimate,
  'schedule' : IDL.Vec(RepaymentRow),
  'principalInterest' : PrincipalInterest,
});
export const BreakEven = IDL.Record({
  'explanation' : IDL.Text,
  'breakEvenSales' : Estimate,
  'breakEvenUnits' : IDL.Opt(Estimate),
  'assumptions' : IDL.Vec(IDL.Text),
});
export const CashRequirement = IDL.Record({
  'total' : Estimate,
  'projectCost' : Estimate,
  'buffer' : Estimate,
  'workingCapital' : Estimate,
});
export const OperatingCosts = IDL.Record({
  'rawMaterial' : IDL.Nat,
  'salary' : IDL.Nat,
  'other' : IDL.Nat,
  'marketing' : IDL.Nat,
  'rent' : IDL.Nat,
  'transport' : IDL.Nat,
  'electricity' : IDL.Nat,
  'maintenance' : IDL.Nat,
  'packaging' : IDL.Nat,
});
export const WorkingCapitalInput = IDL.Record({
  'initialRequirement' : IDL.Nat,
  'monthlyRequirement' : IDL.Nat,
  'emergencyBufferPercent' : IDL.Nat,
});
export const FinanceInput = IDL.Record({
  'operatingCosts' : OperatingCosts,
  'moratoriumMonths' : IDL.Nat,
  'pricePerUnit' : IDL.Nat,
  'loanRequirement' : IDL.Nat,
  'ownCapital' : IDL.Nat,
  'tenureMonths' : IDL.Nat,
  'proposedProjectCost' : IDL.Nat,
  'variableCostPerUnit' : IDL.Nat,
  'interestRatePercent' : IDL.Nat,
  'marginPercent' : IDL.Nat,
  'workingCapital' : WorkingCapitalInput,
});
export const SchemeRule = IDL.Record({
  'maxProjectCost' : IDL.Nat,
  'moratoriumMonths' : IDL.Nat,
  'name' : IDL.Text,
  'loanPercent' : IDL.Nat,
  'tenureMonths' : IDL.Nat,
  'beneficiaryContributionPercent' : IDL.Nat,
  'interestRatePercent' : IDL.Nat,
  'minProjectCost' : IDL.Nat,
});
export const Moratorium = IDL.Record({
  'moratoriumMonths' : IDL.Nat,
  'explanation' : IDL.Text,
  'repaymentStartMonth' : IDL.Nat,
  'interestAccruedDuringMoratorium' : Estimate,
});
export const Financing = IDL.Record({
  'loanAmount' : Estimate,
  'scheme' : SchemeRule,
  'feasibleProjectCost' : Estimate,
  'beneficiaryContribution' : Estimate,
  'maximumLoan' : Estimate,
});
export const WorkingCapital = IDL.Record({
  'initialRequirement' : Estimate,
  'emergencyBuffer' : Estimate,
  'totalRequirement' : Estimate,
  'monthlyRequirement' : Estimate,
});
export const FinancialPlan = IDL.Record({
  'moratorium' : Moratorium,
  'breakEven' : BreakEven,
  'financing' : Financing,
  'workingCapital' : WorkingCapital,
  'cashRequirement' : CashRequirement,
  'monthlyOperatingCost' : Estimate,
  'amortization' : Amortization,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Competitor = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'name' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'priceRangeAvg' : IDL.Nat,
  'priceRangeMax' : IDL.Nat,
  'priceRangeMin' : IDL.Nat,
});
export const MapData = IDL.Record({
  'businessClusters' : IDL.Vec(IDL.Text),
  'underservedZones' : IDL.Vec(IDL.Text),
  'userLocation' : IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 }),
  'reliableDataAvailable' : IDL.Bool,
  'competitors' : IDL.Vec(Competitor),
  'averageDistance' : IDL.Float64,
  'nearestCompetitors' : IDL.Vec(Competitor),
  'competitorDensity' : IDL.Float64,
});
export const ScoreCard = IDL.Record({
  'explanation' : IDL.Text,
  'reasoning' : IDL.Text,
  'score' : IDL.Nat,
});
export const Scores = IDL.Record({
  'supplyGap' : ScoreCard,
  'demand' : ScoreCard,
  'competition' : ScoreCard,
  'opportunity' : ScoreCard,
});
export const RiskLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const RiskCategory = IDL.Record({
  'why' : IDL.Text,
  'whatToDo' : IDL.Text,
  'level' : RiskLevel,
  'category' : IDL.Text,
});
export const RiskAssessment = IDL.Record({
  'categories' : IDL.Vec(RiskCategory),
});
export const SWOT = IDL.Record({
  'weaknesses' : IDL.Vec(IDL.Text),
  'strengths' : IDL.Vec(IDL.Text),
  'threats' : IDL.Vec(IDL.Text),
  'opportunities' : IDL.Vec(IDL.Text),
});
export const Pricing = IDL.Record({
  'packagingCost' : Estimate,
  'recommendedPriceRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  'productionCost' : Estimate,
  'transportCost' : Estimate,
  'competitorPriceRange' : IDL.Record({
    'avg' : IDL.Nat,
    'max' : IDL.Nat,
    'min' : IDL.Nat,
  }),
  'operatingCost' : Estimate,
  'estimatedMargin' : Estimate,
});
export const MarketReach = IDL.Record({
  'demandIndicators' : IDL.Vec(IDL.Text),
  'potentialCustomerBase' : Estimate,
  'competitionLevel' : IDL.Text,
  'nearbyMarkets' : IDL.Vec(IDL.Text),
  'estimatedReach' : Estimate,
  'supplyIndicators' : IDL.Vec(IDL.Text),
  'underservedOpportunities' : IDL.Vec(IDL.Text),
  'distributionChannels' : IDL.Vec(IDL.Text),
  'accessibility' : IDL.Text,
});
export const AnalysisResult = IDL.Record({
  'map' : MapData,
  'scores' : Scores,
  'risk' : RiskAssessment,
  'swot' : SWOT,
  'pricing' : Pricing,
  'market' : MarketReach,
});
export const Radius = IDL.Variant({ 'R5km' : IDL.Null, 'R10km' : IDL.Null });
export const AnalysisInput = IDL.Record({
  'district' : IDL.Text,
  'state' : IDL.Text,
  'village' : IDL.Text,
  'capital' : IDL.Nat,
  'category' : IDL.Text,
  'block' : IDL.Text,
});
export const Analysis = IDL.Record({
  'id' : IDL.Nat,
  'result' : AnalysisResult,
  'createdAt' : IDL.Int,
  'radius' : Radius,
  'input' : AnalysisInput,
});
export const SchemeStatus = IDL.Variant({
  'UnderReview' : IDL.Null,
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const ProjectCostRange = IDL.Record({
  'max' : IDL.Nat,
  'min' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const Scheme = IDL.Record({
  'id' : IDL.Nat,
  'status' : SchemeStatus,
  'documents' : IDL.Vec(IDL.Text),
  'moratoriumMonths' : IDL.Opt(IDL.Nat),
  'projectCostRange' : ProjectCostRange,
  'beneficiaryType' : IDL.Text,
  'marginRequirement' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'eligibility' : IDL.Text,
  'tenureMonths' : IDL.Opt(IDL.Nat),
  'loanPercentage' : IDL.Opt(IDL.Nat),
  'interestRate' : IDL.Opt(IDL.Float64),
  'lastVerifiedDate' : Timestamp,
  'officialSource' : IDL.Text,
});
export const SchemeRoutingInput = IDL.Record({
  'projectCost' : IDL.Nat,
  'businessCategory' : IDL.Text,
  'beneficiaryCategory' : IDL.Text,
  'contribution' : IDL.Nat,
  'location' : IDL.Text,
});
export const SchemeMatch = IDL.Record({
  'moratoriumMonths' : IDL.Opt(IDL.Nat),
  'requiredDocuments' : IDL.Vec(IDL.Text),
  'scheme' : Scheme,
  'loan' : IDL.Opt(IDL.Nat),
  'officialVerificationNote' : IDL.Text,
  'tenureMonths' : IDL.Opt(IDL.Nat),
  'interestRate' : IDL.Opt(IDL.Float64),
  'projectCostLimit' : ProjectCostRange,
  'contribution' : IDL.Opt(IDL.Nat),
  'whyMayFit' : IDL.Text,
});
export const SchemeRoutingResult = IDL.Record({
  'heading' : IDL.Text,
  'matches' : IDL.Vec(SchemeMatch),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chat' : IDL.Func([ChatRequest], [ChatResponse], []),
  'computeAmortization' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [Amortization],
      ['query'],
    ),
  'computeBreakEven' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [BreakEven],
      ['query'],
    ),
  'computeCashRequirement' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [CashRequirement],
      ['query'],
    ),
  'computeFinancialPlan' : IDL.Func(
      [FinanceInput, SchemeRule],
      [FinancialPlan],
      ['query'],
    ),
  'computeFinancing' : IDL.Func(
      [FinanceInput, SchemeRule],
      [Financing],
      ['query'],
    ),
  'computeMoratorium' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [Moratorium],
      ['query'],
    ),
  'computeWorkingCapital' : IDL.Func(
      [WorkingCapitalInput],
      [WorkingCapital],
      ['query'],
    ),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAnalysis' : IDL.Func([IDL.Nat], [IDL.Opt(Analysis)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getScheme' : IDL.Func([IDL.Nat], [IDL.Opt(Scheme)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAnalyses' : IDL.Func([], [IDL.Vec(Analysis)], ['query']),
  'listSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
  'routeSchemes' : IDL.Func(
      [SchemeRoutingInput],
      [SchemeRoutingResult],
      ['query'],
    ),
  'runAnalysis' : IDL.Func([AnalysisInput, Radius], [AnalysisResult], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null }),
  });
  const ChatRequest = IDL.Record({
    'history' : IDL.Vec(ChatMessage),
    'analysisId' : IDL.Nat,
    'message' : IDL.Text,
  });
  const ChatResponse = IDL.Record({ 'reply' : IDL.Text });
  const Provenance = IDL.Variant({
    'Estimated' : IDL.Null,
    'UserProvided' : IDL.Null,
    'Calculated' : IDL.Null,
    'Observed' : IDL.Null,
  });
  const Confidence = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Estimate = IDL.Record({
    'provenance' : Provenance,
    'value' : IDL.Nat,
    'confidence' : Confidence,
  });
  const RepaymentRow = IDL.Record({
    'emi' : IDL.Nat,
    'month' : IDL.Nat,
    'principal' : IDL.Nat,
    'interest' : IDL.Nat,
    'closingBalance' : IDL.Nat,
    'openingBalance' : IDL.Nat,
  });
  const PrincipalInterest = IDL.Record({
    'totalRepayment' : IDL.Nat,
    'totalInterest' : IDL.Nat,
    'totalPrincipal' : IDL.Nat,
  });
  const Amortization = IDL.Record({
    'emi' : Estimate,
    'totalRepayment' : Estimate,
    'totalInterest' : Estimate,
    'schedule' : IDL.Vec(RepaymentRow),
    'principalInterest' : PrincipalInterest,
  });
  const BreakEven = IDL.Record({
    'explanation' : IDL.Text,
    'breakEvenSales' : Estimate,
    'breakEvenUnits' : IDL.Opt(Estimate),
    'assumptions' : IDL.Vec(IDL.Text),
  });
  const CashRequirement = IDL.Record({
    'total' : Estimate,
    'projectCost' : Estimate,
    'buffer' : Estimate,
    'workingCapital' : Estimate,
  });
  const OperatingCosts = IDL.Record({
    'rawMaterial' : IDL.Nat,
    'salary' : IDL.Nat,
    'other' : IDL.Nat,
    'marketing' : IDL.Nat,
    'rent' : IDL.Nat,
    'transport' : IDL.Nat,
    'electricity' : IDL.Nat,
    'maintenance' : IDL.Nat,
    'packaging' : IDL.Nat,
  });
  const WorkingCapitalInput = IDL.Record({
    'initialRequirement' : IDL.Nat,
    'monthlyRequirement' : IDL.Nat,
    'emergencyBufferPercent' : IDL.Nat,
  });
  const FinanceInput = IDL.Record({
    'operatingCosts' : OperatingCosts,
    'moratoriumMonths' : IDL.Nat,
    'pricePerUnit' : IDL.Nat,
    'loanRequirement' : IDL.Nat,
    'ownCapital' : IDL.Nat,
    'tenureMonths' : IDL.Nat,
    'proposedProjectCost' : IDL.Nat,
    'variableCostPerUnit' : IDL.Nat,
    'interestRatePercent' : IDL.Nat,
    'marginPercent' : IDL.Nat,
    'workingCapital' : WorkingCapitalInput,
  });
  const SchemeRule = IDL.Record({
    'maxProjectCost' : IDL.Nat,
    'moratoriumMonths' : IDL.Nat,
    'name' : IDL.Text,
    'loanPercent' : IDL.Nat,
    'tenureMonths' : IDL.Nat,
    'beneficiaryContributionPercent' : IDL.Nat,
    'interestRatePercent' : IDL.Nat,
    'minProjectCost' : IDL.Nat,
  });
  const Moratorium = IDL.Record({
    'moratoriumMonths' : IDL.Nat,
    'explanation' : IDL.Text,
    'repaymentStartMonth' : IDL.Nat,
    'interestAccruedDuringMoratorium' : Estimate,
  });
  const Financing = IDL.Record({
    'loanAmount' : Estimate,
    'scheme' : SchemeRule,
    'feasibleProjectCost' : Estimate,
    'beneficiaryContribution' : Estimate,
    'maximumLoan' : Estimate,
  });
  const WorkingCapital = IDL.Record({
    'initialRequirement' : Estimate,
    'emergencyBuffer' : Estimate,
    'totalRequirement' : Estimate,
    'monthlyRequirement' : Estimate,
  });
  const FinancialPlan = IDL.Record({
    'moratorium' : Moratorium,
    'breakEven' : BreakEven,
    'financing' : Financing,
    'workingCapital' : WorkingCapital,
    'cashRequirement' : CashRequirement,
    'monthlyOperatingCost' : Estimate,
    'amortization' : Amortization,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Competitor = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'name' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'priceRangeAvg' : IDL.Nat,
    'priceRangeMax' : IDL.Nat,
    'priceRangeMin' : IDL.Nat,
  });
  const MapData = IDL.Record({
    'businessClusters' : IDL.Vec(IDL.Text),
    'underservedZones' : IDL.Vec(IDL.Text),
    'userLocation' : IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 }),
    'reliableDataAvailable' : IDL.Bool,
    'competitors' : IDL.Vec(Competitor),
    'averageDistance' : IDL.Float64,
    'nearestCompetitors' : IDL.Vec(Competitor),
    'competitorDensity' : IDL.Float64,
  });
  const ScoreCard = IDL.Record({
    'explanation' : IDL.Text,
    'reasoning' : IDL.Text,
    'score' : IDL.Nat,
  });
  const Scores = IDL.Record({
    'supplyGap' : ScoreCard,
    'demand' : ScoreCard,
    'competition' : ScoreCard,
    'opportunity' : ScoreCard,
  });
  const RiskLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const RiskCategory = IDL.Record({
    'why' : IDL.Text,
    'whatToDo' : IDL.Text,
    'level' : RiskLevel,
    'category' : IDL.Text,
  });
  const RiskAssessment = IDL.Record({ 'categories' : IDL.Vec(RiskCategory) });
  const SWOT = IDL.Record({
    'weaknesses' : IDL.Vec(IDL.Text),
    'strengths' : IDL.Vec(IDL.Text),
    'threats' : IDL.Vec(IDL.Text),
    'opportunities' : IDL.Vec(IDL.Text),
  });
  const Pricing = IDL.Record({
    'packagingCost' : Estimate,
    'recommendedPriceRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
    'productionCost' : Estimate,
    'transportCost' : Estimate,
    'competitorPriceRange' : IDL.Record({
      'avg' : IDL.Nat,
      'max' : IDL.Nat,
      'min' : IDL.Nat,
    }),
    'operatingCost' : Estimate,
    'estimatedMargin' : Estimate,
  });
  const MarketReach = IDL.Record({
    'demandIndicators' : IDL.Vec(IDL.Text),
    'potentialCustomerBase' : Estimate,
    'competitionLevel' : IDL.Text,
    'nearbyMarkets' : IDL.Vec(IDL.Text),
    'estimatedReach' : Estimate,
    'supplyIndicators' : IDL.Vec(IDL.Text),
    'underservedOpportunities' : IDL.Vec(IDL.Text),
    'distributionChannels' : IDL.Vec(IDL.Text),
    'accessibility' : IDL.Text,
  });
  const AnalysisResult = IDL.Record({
    'map' : MapData,
    'scores' : Scores,
    'risk' : RiskAssessment,
    'swot' : SWOT,
    'pricing' : Pricing,
    'market' : MarketReach,
  });
  const Radius = IDL.Variant({ 'R5km' : IDL.Null, 'R10km' : IDL.Null });
  const AnalysisInput = IDL.Record({
    'district' : IDL.Text,
    'state' : IDL.Text,
    'village' : IDL.Text,
    'capital' : IDL.Nat,
    'category' : IDL.Text,
    'block' : IDL.Text,
  });
  const Analysis = IDL.Record({
    'id' : IDL.Nat,
    'result' : AnalysisResult,
    'createdAt' : IDL.Int,
    'radius' : Radius,
    'input' : AnalysisInput,
  });
  const SchemeStatus = IDL.Variant({
    'UnderReview' : IDL.Null,
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const ProjectCostRange = IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat });
  const Timestamp = IDL.Int;
  const Scheme = IDL.Record({
    'id' : IDL.Nat,
    'status' : SchemeStatus,
    'documents' : IDL.Vec(IDL.Text),
    'moratoriumMonths' : IDL.Opt(IDL.Nat),
    'projectCostRange' : ProjectCostRange,
    'beneficiaryType' : IDL.Text,
    'marginRequirement' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'eligibility' : IDL.Text,
    'tenureMonths' : IDL.Opt(IDL.Nat),
    'loanPercentage' : IDL.Opt(IDL.Nat),
    'interestRate' : IDL.Opt(IDL.Float64),
    'lastVerifiedDate' : Timestamp,
    'officialSource' : IDL.Text,
  });
  const SchemeRoutingInput = IDL.Record({
    'projectCost' : IDL.Nat,
    'businessCategory' : IDL.Text,
    'beneficiaryCategory' : IDL.Text,
    'contribution' : IDL.Nat,
    'location' : IDL.Text,
  });
  const SchemeMatch = IDL.Record({
    'moratoriumMonths' : IDL.Opt(IDL.Nat),
    'requiredDocuments' : IDL.Vec(IDL.Text),
    'scheme' : Scheme,
    'loan' : IDL.Opt(IDL.Nat),
    'officialVerificationNote' : IDL.Text,
    'tenureMonths' : IDL.Opt(IDL.Nat),
    'interestRate' : IDL.Opt(IDL.Float64),
    'projectCostLimit' : ProjectCostRange,
    'contribution' : IDL.Opt(IDL.Nat),
    'whyMayFit' : IDL.Text,
  });
  const SchemeRoutingResult = IDL.Record({
    'heading' : IDL.Text,
    'matches' : IDL.Vec(SchemeMatch),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chat' : IDL.Func([ChatRequest], [ChatResponse], []),
    'computeAmortization' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [Amortization],
        ['query'],
      ),
    'computeBreakEven' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [BreakEven],
        ['query'],
      ),
    'computeCashRequirement' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [CashRequirement],
        ['query'],
      ),
    'computeFinancialPlan' : IDL.Func(
        [FinanceInput, SchemeRule],
        [FinancialPlan],
        ['query'],
      ),
    'computeFinancing' : IDL.Func(
        [FinanceInput, SchemeRule],
        [Financing],
        ['query'],
      ),
    'computeMoratorium' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [Moratorium],
        ['query'],
      ),
    'computeWorkingCapital' : IDL.Func(
        [WorkingCapitalInput],
        [WorkingCapital],
        ['query'],
      ),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAnalysis' : IDL.Func([IDL.Nat], [IDL.Opt(Analysis)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getScheme' : IDL.Func([IDL.Nat], [IDL.Opt(Scheme)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAnalyses' : IDL.Func([], [IDL.Vec(Analysis)], ['query']),
    'listSchemes' : IDL.Func([], [IDL.Vec(Scheme)], ['query']),
    'routeSchemes' : IDL.Func(
        [SchemeRoutingInput],
        [SchemeRoutingResult],
        ['query'],
      ),
    'runAnalysis' : IDL.Func([AnalysisInput, Radius], [AnalysisResult], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };