/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Amortization {
  'emi' : Estimate,
  'totalRepayment' : Estimate,
  'totalInterest' : Estimate,
  'schedule' : Array<RepaymentRow>,
  'principalInterest' : PrincipalInterest,
}
export interface Analysis {
  'id' : bigint,
  'result' : AnalysisResult,
  'createdAt' : bigint,
  'radius' : Radius,
  'input' : AnalysisInput,
}
export interface AnalysisInput {
  'district' : string,
  'state' : string,
  'village' : string,
  'capital' : bigint,
  'category' : string,
  'block' : string,
}
export interface AnalysisResult {
  'map' : MapData,
  'scores' : Scores,
  'risk' : RiskAssessment,
  'swot' : SWOT,
  'pricing' : Pricing,
  'market' : MarketReach,
}
export interface BreakEven {
  'explanation' : string,
  'breakEvenSales' : Estimate,
  'breakEvenUnits' : [] | [Estimate],
  'assumptions' : Array<string>,
}
export interface CashRequirement {
  'total' : Estimate,
  'projectCost' : Estimate,
  'buffer' : Estimate,
  'workingCapital' : Estimate,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ChatMessage {
  'content' : string,
  'role' : { 'user' : null } |
    { 'assistant' : null },
}
export interface ChatRequest {
  'history' : Array<ChatMessage>,
  'analysisId' : bigint,
  'message' : string,
}
export interface ChatResponse { 'reply' : string }
export interface Competitor {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'name' : string,
  'distanceKm' : number,
  'priceRangeAvg' : bigint,
  'priceRangeMax' : bigint,
  'priceRangeMin' : bigint,
}
export type Confidence = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Estimate {
  'provenance' : Provenance,
  'value' : bigint,
  'confidence' : Confidence,
}
export interface FinanceInput {
  'operatingCosts' : OperatingCosts,
  'moratoriumMonths' : bigint,
  'pricePerUnit' : bigint,
  'loanRequirement' : bigint,
  'ownCapital' : bigint,
  'tenureMonths' : bigint,
  'proposedProjectCost' : bigint,
  'variableCostPerUnit' : bigint,
  'interestRatePercent' : bigint,
  'marginPercent' : bigint,
  'workingCapital' : WorkingCapitalInput,
}
export interface FinancialPlan {
  'moratorium' : Moratorium,
  'breakEven' : BreakEven,
  'financing' : Financing,
  'workingCapital' : WorkingCapital,
  'cashRequirement' : CashRequirement,
  'monthlyOperatingCost' : Estimate,
  'amortization' : Amortization,
}
export interface Financing {
  'loanAmount' : Estimate,
  'scheme' : SchemeRule,
  'feasibleProjectCost' : Estimate,
  'beneficiaryContribution' : Estimate,
  'maximumLoan' : Estimate,
}
export interface MapData {
  'businessClusters' : Array<string>,
  'underservedZones' : Array<string>,
  'userLocation' : { 'lat' : number, 'lng' : number },
  'reliableDataAvailable' : boolean,
  'competitors' : Array<Competitor>,
  'averageDistance' : number,
  'nearestCompetitors' : Array<Competitor>,
  'competitorDensity' : number,
}
export interface MarketReach {
  'demandIndicators' : Array<string>,
  'potentialCustomerBase' : Estimate,
  'competitionLevel' : string,
  'nearbyMarkets' : Array<string>,
  'estimatedReach' : Estimate,
  'supplyIndicators' : Array<string>,
  'underservedOpportunities' : Array<string>,
  'distributionChannels' : Array<string>,
  'accessibility' : string,
}
export interface Moratorium {
  'moratoriumMonths' : bigint,
  'explanation' : string,
  'repaymentStartMonth' : bigint,
  'interestAccruedDuringMoratorium' : Estimate,
}
export interface OperatingCosts {
  'rawMaterial' : bigint,
  'salary' : bigint,
  'other' : bigint,
  'marketing' : bigint,
  'rent' : bigint,
  'transport' : bigint,
  'electricity' : bigint,
  'maintenance' : bigint,
  'packaging' : bigint,
}
export interface Pricing {
  'packagingCost' : Estimate,
  'recommendedPriceRange' : { 'max' : bigint, 'min' : bigint },
  'productionCost' : Estimate,
  'transportCost' : Estimate,
  'competitorPriceRange' : { 'avg' : bigint, 'max' : bigint, 'min' : bigint },
  'operatingCost' : Estimate,
  'estimatedMargin' : Estimate,
}
export interface PrincipalInterest {
  'totalRepayment' : bigint,
  'totalInterest' : bigint,
  'totalPrincipal' : bigint,
}
export interface ProjectCostRange { 'max' : bigint, 'min' : bigint }
export type Provenance = { 'Estimated' : null } |
  { 'UserProvided' : null } |
  { 'Calculated' : null } |
  { 'Observed' : null };
export type Radius = { 'R5km' : null } |
  { 'R10km' : null };
export interface RepaymentRow {
  'emi' : bigint,
  'month' : bigint,
  'principal' : bigint,
  'interest' : bigint,
  'closingBalance' : bigint,
  'openingBalance' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RiskAssessment { 'categories' : Array<RiskCategory> }
export interface RiskCategory {
  'why' : string,
  'whatToDo' : string,
  'level' : RiskLevel,
  'category' : string,
}
export type RiskLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface SWOT {
  'weaknesses' : Array<string>,
  'strengths' : Array<string>,
  'threats' : Array<string>,
  'opportunities' : Array<string>,
}
export interface Scheme {
  'id' : bigint,
  'status' : SchemeStatus,
  'documents' : Array<string>,
  'moratoriumMonths' : [] | [bigint],
  'projectCostRange' : ProjectCostRange,
  'beneficiaryType' : string,
  'marginRequirement' : [] | [bigint],
  'name' : string,
  'eligibility' : string,
  'tenureMonths' : [] | [bigint],
  'loanPercentage' : [] | [bigint],
  'interestRate' : [] | [number],
  'lastVerifiedDate' : Timestamp,
  'officialSource' : string,
}
export interface SchemeMatch {
  'moratoriumMonths' : [] | [bigint],
  'requiredDocuments' : Array<string>,
  'scheme' : Scheme,
  'loan' : [] | [bigint],
  'officialVerificationNote' : string,
  'tenureMonths' : [] | [bigint],
  'interestRate' : [] | [number],
  'projectCostLimit' : ProjectCostRange,
  'contribution' : [] | [bigint],
  'whyMayFit' : string,
}
export interface SchemeRoutingInput {
  'projectCost' : bigint,
  'businessCategory' : string,
  'beneficiaryCategory' : string,
  'contribution' : bigint,
  'location' : string,
}
export interface SchemeRoutingResult {
  'heading' : string,
  'matches' : Array<SchemeMatch>,
}
export interface SchemeRule {
  'maxProjectCost' : bigint,
  'moratoriumMonths' : bigint,
  'name' : string,
  'loanPercent' : bigint,
  'tenureMonths' : bigint,
  'beneficiaryContributionPercent' : bigint,
  'interestRatePercent' : bigint,
  'minProjectCost' : bigint,
}
export type SchemeStatus = { 'UnderReview' : null } |
  { 'Inactive' : null } |
  { 'Active' : null };
export interface ScoreCard {
  'explanation' : string,
  'reasoning' : string,
  'score' : bigint,
}
export interface Scores {
  'supplyGap' : ScoreCard,
  'demand' : ScoreCard,
  'competition' : ScoreCard,
  'opportunity' : ScoreCard,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WorkingCapital {
  'initialRequirement' : Estimate,
  'emergencyBuffer' : Estimate,
  'totalRequirement' : Estimate,
  'monthlyRequirement' : Estimate,
}
export interface WorkingCapitalInput {
  'initialRequirement' : bigint,
  'monthlyRequirement' : bigint,
  'emergencyBufferPercent' : bigint,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chat' : ActorMethod<[ChatRequest], ChatResponse>,
  'computeAmortization' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    Amortization
  >,
  'computeBreakEven' : ActorMethod<[bigint, bigint, bigint], BreakEven>,
  'computeCashRequirement' : ActorMethod<
    [bigint, bigint, bigint],
    CashRequirement
  >,
  'computeFinancialPlan' : ActorMethod<
    [FinanceInput, SchemeRule],
    FinancialPlan
  >,
  'computeFinancing' : ActorMethod<[FinanceInput, SchemeRule], Financing>,
  'computeMoratorium' : ActorMethod<[bigint, bigint, bigint], Moratorium>,
  'computeWorkingCapital' : ActorMethod<[WorkingCapitalInput], WorkingCapital>,
  'execute' : ActorMethod<[string], Result>,
  'getAnalysis' : ActorMethod<[bigint], [] | [Analysis]>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getScheme' : ActorMethod<[bigint], [] | [Scheme]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAnalyses' : ActorMethod<[], Array<Analysis>>,
  'listSchemes' : ActorMethod<[], Array<Scheme>>,
  'routeSchemes' : ActorMethod<[SchemeRoutingInput], SchemeRoutingResult>,
  'runAnalysis' : ActorMethod<[AnalysisInput, Radius], AnalysisResult>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];