/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface SWOT {
    weaknesses: Array<string>;
    strengths: Array<string>;
    threats: Array<string>;
    opportunities: Array<string>;
}
export interface ProjectCostRange {
    max: bigint;
    min: bigint;
}
export type Timestamp = bigint;
export interface WorkingCapitalInput {
    initialRequirement: bigint;
    monthlyRequirement: bigint;
    emergencyBufferPercent: bigint;
}
export interface Pricing {
    packagingCost: Estimate;
    recommendedPriceRange: {
        max: bigint;
        min: bigint;
    };
    productionCost: Estimate;
    transportCost: Estimate;
    competitorPriceRange: {
        avg: bigint;
        max: bigint;
        min: bigint;
    };
    operatingCost: Estimate;
    estimatedMargin: Estimate;
}
export interface Financing {
    loanAmount: Estimate;
    scheme: SchemeRule;
    feasibleProjectCost: Estimate;
    beneficiaryContribution: Estimate;
    maximumLoan: Estimate;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface CashRequirement {
    total: Estimate;
    projectCost: Estimate;
    buffer: Estimate;
    workingCapital: Estimate;
}
export interface RiskAssessment {
    categories: Array<RiskCategory>;
}
export interface Analysis {
    id: bigint;
    result: AnalysisResult;
    createdAt: bigint;
    radius: Radius;
    input: AnalysisInput;
}
export interface MapData {
    businessClusters: Array<string>;
    underservedZones: Array<string>;
    userLocation: {
        lat: number;
        lng: number;
    };
    reliableDataAvailable: boolean;
    competitors: Array<Competitor>;
    averageDistance: number;
    nearestCompetitors: Array<Competitor>;
    competitorDensity: number;
}
export interface WorkingCapital {
    initialRequirement: Estimate;
    emergencyBuffer: Estimate;
    totalRequirement: Estimate;
    monthlyRequirement: Estimate;
}
export interface Amortization {
    emi: Estimate;
    totalRepayment: Estimate;
    totalInterest: Estimate;
    schedule: Array<RepaymentRow>;
    principalInterest: PrincipalInterest;
}
export interface AnalysisInput {
    district: string;
    state: string;
    village: string;
    capital: bigint;
    category: string;
    block: string;
}
export interface ChatRequest {
    history: Array<ChatMessage>;
    analysisId: bigint;
    message: string;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface ChatMessage {
    content: string;
    role: Variant_user_assistant;
}
export interface SchemeRule {
    maxProjectCost: bigint;
    moratoriumMonths: bigint;
    name: string;
    loanPercent: bigint;
    tenureMonths: bigint;
    beneficiaryContributionPercent: bigint;
    interestRatePercent: bigint;
    minProjectCost: bigint;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface RepaymentRow {
    emi: bigint;
    month: bigint;
    principal: bigint;
    interest: bigint;
    closingBalance: bigint;
    openingBalance: bigint;
}
export interface FinanceInput {
    operatingCosts: OperatingCosts;
    moratoriumMonths: bigint;
    pricePerUnit: bigint;
    loanRequirement: bigint;
    ownCapital: bigint;
    tenureMonths: bigint;
    proposedProjectCost: bigint;
    variableCostPerUnit: bigint;
    interestRatePercent: bigint;
    marginPercent: bigint;
    workingCapital: WorkingCapitalInput;
}
export interface AnalysisResult {
    map: MapData;
    scores: Scores;
    risk: RiskAssessment;
    swot: SWOT;
    pricing: Pricing;
    market: MarketReach;
}
export interface SchemeRoutingResult {
    heading: string;
    matches: Array<SchemeMatch>;
}
export interface SchemeRoutingInput {
    projectCost: bigint;
    businessCategory: string;
    beneficiaryCategory: string;
    contribution: bigint;
    location: string;
}
export interface SchemeMatch {
    moratoriumMonths?: bigint;
    requiredDocuments: Array<string>;
    scheme: Scheme;
    loan?: bigint;
    officialVerificationNote: string;
    tenureMonths?: bigint;
    interestRate?: number;
    projectCostLimit: ProjectCostRange;
    contribution?: bigint;
    whyMayFit: string;
}
export interface FinancialPlan {
    moratorium: Moratorium;
    breakEven: BreakEven;
    financing: Financing;
    workingCapital: WorkingCapital;
    cashRequirement: CashRequirement;
    monthlyOperatingCost: Estimate;
    amortization: Amortization;
}
export interface BreakEven {
    explanation: string;
    breakEvenSales: Estimate;
    breakEvenUnits?: Estimate;
    assumptions: Array<string>;
}
export interface ScoreCard {
    explanation: string;
    reasoning: string;
    score: bigint;
}
export interface PrincipalInterest {
    totalRepayment: bigint;
    totalInterest: bigint;
    totalPrincipal: bigint;
}
export interface Scheme {
    id: bigint;
    status: SchemeStatus;
    documents: Array<string>;
    moratoriumMonths?: bigint;
    projectCostRange: ProjectCostRange;
    beneficiaryType: string;
    marginRequirement?: bigint;
    name: string;
    eligibility: string;
    tenureMonths?: bigint;
    loanPercentage?: bigint;
    interestRate?: number;
    lastVerifiedDate: Timestamp;
    officialSource: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Competitor {
    id: bigint;
    lat: number;
    lng: number;
    name: string;
    distanceKm: number;
    priceRangeAvg: bigint;
    priceRangeMax: bigint;
    priceRangeMin: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface RiskCategory {
    why: string;
    whatToDo: string;
    level: RiskLevel;
    category: string;
}
export interface ChatResponse {
    reply: string;
}
export interface Scores {
    supplyGap: ScoreCard;
    demand: ScoreCard;
    competition: ScoreCard;
    opportunity: ScoreCard;
}
export interface Estimate {
    provenance: Provenance;
    value: bigint;
    confidence: Confidence;
}
export interface OperatingCosts {
    rawMaterial: bigint;
    salary: bigint;
    other: bigint;
    marketing: bigint;
    rent: bigint;
    transport: bigint;
    electricity: bigint;
    maintenance: bigint;
    packaging: bigint;
}
export interface MarketReach {
    demandIndicators: Array<string>;
    potentialCustomerBase: Estimate;
    competitionLevel: string;
    nearbyMarkets: Array<string>;
    estimatedReach: Estimate;
    supplyIndicators: Array<string>;
    underservedOpportunities: Array<string>;
    distributionChannels: Array<string>;
    accessibility: string;
}
export interface Moratorium {
    moratoriumMonths: bigint;
    explanation: string;
    repaymentStartMonth: bigint;
    interestAccruedDuringMoratorium: Estimate;
}
export enum Confidence {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum Provenance {
    Estimated = "Estimated",
    UserProvided = "UserProvided",
    Calculated = "Calculated",
    Observed = "Observed"
}
export enum Radius {
    R5km = "R5km",
    R10km = "R10km"
}
export enum SchemeStatus {
    UnderReview = "UnderReview",
    Inactive = "Inactive",
    Active = "Active"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_user_assistant {
    user = "user",
    assistant = "assistant"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    chat(request: ChatRequest): Promise<ChatResponse>;
    computeAmortization(loanAmount: bigint, interestRatePercent: bigint, tenureMonths: bigint, moratoriumMonths: bigint): Promise<Amortization>;
    computeBreakEven(fixedCosts: bigint, variableCostPerUnit: bigint, pricePerUnit: bigint): Promise<BreakEven>;
    computeCashRequirement(feasibleProjectCost: bigint, workingCapitalTotal: bigint, buffer: bigint): Promise<CashRequirement>;
    computeFinancialPlan(input: FinanceInput, rule: SchemeRule): Promise<FinancialPlan>;
    computeFinancing(input: FinanceInput, rule: SchemeRule): Promise<Financing>;
    computeMoratorium(loanAmount: bigint, interestRatePercent: bigint, moratoriumMonths: bigint): Promise<Moratorium>;
    computeWorkingCapital(input: WorkingCapitalInput): Promise<WorkingCapital>;
    execute(qJson: string): Promise<Result>;
    getAnalysis(id: bigint): Promise<Analysis | null>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getScheme(id: bigint): Promise<Scheme | null>;
    isCallerAdmin(): Promise<boolean>;
    listAnalyses(): Promise<Array<Analysis>>;
    listSchemes(): Promise<Array<Scheme>>;
    routeSchemes(input: SchemeRoutingInput): Promise<SchemeRoutingResult>;
    runAnalysis(input: AnalysisInput, radius: Radius): Promise<AnalysisResult>;
    schema(): Promise<string>;
}
import type { Amortization as _Amortization, Analysis as _Analysis, AnalysisInput as _AnalysisInput, AnalysisResult as _AnalysisResult, BreakEven as _BreakEven, CashRequirement as _CashRequirement, Cell as _Cell, ChatMessage as _ChatMessage, ChatRequest as _ChatRequest, Confidence as _Confidence, Error as _Error, Estimate as _Estimate, FinancialPlan as _FinancialPlan, Financing as _Financing, MapData as _MapData, MarketReach as _MarketReach, Moratorium as _Moratorium, Pricing as _Pricing, PrincipalInterest as _PrincipalInterest, ProjectCostRange as _ProjectCostRange, Provenance as _Provenance, Radius as _Radius, RepaymentRow as _RepaymentRow, Result as _Result, Result__1 as _Result__1, RiskAssessment as _RiskAssessment, RiskCategory as _RiskCategory, RiskLevel as _RiskLevel, SWOT as _SWOT, Scheme as _Scheme, SchemeMatch as _SchemeMatch, SchemeRoutingResult as _SchemeRoutingResult, SchemeRule as _SchemeRule, SchemeStatus as _SchemeStatus, Scores as _Scores, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, WorkingCapital as _WorkingCapital } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async chat(arg0: ChatRequest): Promise<ChatResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.chat(to_candid_ChatRequest_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chat(to_candid_ChatRequest_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async computeAmortization(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<Amortization> {
        if (this.processError) {
            try {
                const result = await this.actor.computeAmortization(arg0, arg1, arg2, arg3);
                return from_candid_Amortization_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeAmortization(arg0, arg1, arg2, arg3);
            return from_candid_Amortization_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async computeBreakEven(arg0: bigint, arg1: bigint, arg2: bigint): Promise<BreakEven> {
        if (this.processError) {
            try {
                const result = await this.actor.computeBreakEven(arg0, arg1, arg2);
                return from_candid_BreakEven_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeBreakEven(arg0, arg1, arg2);
            return from_candid_BreakEven_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async computeCashRequirement(arg0: bigint, arg1: bigint, arg2: bigint): Promise<CashRequirement> {
        if (this.processError) {
            try {
                const result = await this.actor.computeCashRequirement(arg0, arg1, arg2);
                return from_candid_CashRequirement_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeCashRequirement(arg0, arg1, arg2);
            return from_candid_CashRequirement_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async computeFinancialPlan(arg0: FinanceInput, arg1: SchemeRule): Promise<FinancialPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.computeFinancialPlan(arg0, arg1);
                return from_candid_FinancialPlan_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeFinancialPlan(arg0, arg1);
            return from_candid_FinancialPlan_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async computeFinancing(arg0: FinanceInput, arg1: SchemeRule): Promise<Financing> {
        if (this.processError) {
            try {
                const result = await this.actor.computeFinancing(arg0, arg1);
                return from_candid_Financing_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeFinancing(arg0, arg1);
            return from_candid_Financing_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async computeMoratorium(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Moratorium> {
        if (this.processError) {
            try {
                const result = await this.actor.computeMoratorium(arg0, arg1, arg2);
                return from_candid_Moratorium_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeMoratorium(arg0, arg1, arg2);
            return from_candid_Moratorium_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async computeWorkingCapital(arg0: WorkingCapitalInput): Promise<WorkingCapital> {
        if (this.processError) {
            try {
                const result = await this.actor.computeWorkingCapital(arg0);
                return from_candid_WorkingCapital_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.computeWorkingCapital(arg0);
            return from_candid_WorkingCapital_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysis(arg0: bigint): Promise<Analysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScheme(arg0: bigint): Promise<Scheme | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheme(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheme(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAnalyses(): Promise<Array<Analysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnalyses();
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnalyses();
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSchemes(): Promise<Array<Scheme>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSchemes();
                return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSchemes();
            return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async routeSchemes(arg0: SchemeRoutingInput): Promise<SchemeRoutingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.routeSchemes(arg0);
                return from_candid_SchemeRoutingResult_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.routeSchemes(arg0);
            return from_candid_SchemeRoutingResult_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async runAnalysis(arg0: AnalysisInput, arg1: Radius): Promise<AnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.runAnalysis(arg0, to_candid_Radius_n75(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AnalysisResult_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runAnalysis(arg0, to_candid_Radius_n75(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AnalysisResult_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
}
function from_candid_Amortization_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Amortization): Amortization {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_AnalysisResult_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisResult): AnalysisResult {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Analysis_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Analysis): Analysis {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_BreakEven_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BreakEven): BreakEven {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_CashRequirement_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CashRequirement): CashRequirement {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Confidence_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Confidence): Confidence {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Estimate_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Estimate): Estimate {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_FinancialPlan_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialPlan): FinancialPlan {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Financing_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Financing): Financing {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_MarketReach_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketReach): MarketReach {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_Moratorium_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Moratorium): Moratorium {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Pricing_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pricing): Pricing {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Provenance_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Provenance): Provenance {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Radius_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Radius): Radius {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_RiskAssessment_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskAssessment): RiskAssessment {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_RiskCategory_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskCategory): RiskCategory {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_SchemeMatch_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SchemeMatch): SchemeMatch {
    return from_candid_record_n74(_uploadFile, _downloadFile, value);
}
function from_candid_SchemeRoutingResult_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SchemeRoutingResult): SchemeRoutingResult {
    return from_candid_record_n71(_uploadFile, _downloadFile, value);
}
function from_candid_SchemeStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SchemeStatus): SchemeStatus {
    return from_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function from_candid_Scheme_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Scheme): Scheme {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_WorkingCapital_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkingCapital): WorkingCapital {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Estimate]): Estimate | null {
    return value.length === 0 ? null : from_candid_Estimate_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Analysis]): Analysis | null {
    return value.length === 0 ? null : from_candid_Analysis_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Scheme]): Scheme | null {
    return value.length === 0 ? null : from_candid_Scheme_n62(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emi: _Estimate;
    totalRepayment: _Estimate;
    totalInterest: _Estimate;
    schedule: Array<_RepaymentRow>;
    principalInterest: _PrincipalInterest;
}): {
    emi: Estimate;
    totalRepayment: Estimate;
    totalInterest: Estimate;
    schedule: Array<RepaymentRow>;
    principalInterest: PrincipalInterest;
} {
    return {
        emi: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.emi),
        totalRepayment: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.totalRepayment),
        totalInterest: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.totalInterest),
        schedule: value.schedule,
        principalInterest: value.principalInterest
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    provenance: _Provenance;
    value: bigint;
    confidence: _Confidence;
}): {
    provenance: Provenance;
    value: bigint;
    confidence: Confidence;
} {
    return {
        provenance: from_candid_Provenance_n17(_uploadFile, _downloadFile, value.provenance),
        value: value.value,
        confidence: from_candid_Confidence_n19(_uploadFile, _downloadFile, value.confidence)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    explanation: string;
    breakEvenSales: _Estimate;
    breakEvenUnits: [] | [_Estimate];
    assumptions: Array<string>;
}): {
    explanation: string;
    breakEvenSales: Estimate;
    breakEvenUnits?: Estimate;
    assumptions: Array<string>;
} {
    return {
        explanation: value.explanation,
        breakEvenSales: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.breakEvenSales),
        breakEvenUnits: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.breakEvenUnits)),
        assumptions: value.assumptions
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: _Estimate;
    projectCost: _Estimate;
    buffer: _Estimate;
    workingCapital: _Estimate;
}): {
    total: Estimate;
    projectCost: Estimate;
    buffer: Estimate;
    workingCapital: Estimate;
} {
    return {
        total: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.total),
        projectCost: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.projectCost),
        buffer: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.buffer),
        workingCapital: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.workingCapital)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moratorium: _Moratorium;
    breakEven: _BreakEven;
    financing: _Financing;
    workingCapital: _WorkingCapital;
    cashRequirement: _CashRequirement;
    monthlyOperatingCost: _Estimate;
    amortization: _Amortization;
}): {
    moratorium: Moratorium;
    breakEven: BreakEven;
    financing: Financing;
    workingCapital: WorkingCapital;
    cashRequirement: CashRequirement;
    monthlyOperatingCost: Estimate;
    amortization: Amortization;
} {
    return {
        moratorium: from_candid_Moratorium_n28(_uploadFile, _downloadFile, value.moratorium),
        breakEven: from_candid_BreakEven_n21(_uploadFile, _downloadFile, value.breakEven),
        financing: from_candid_Financing_n30(_uploadFile, _downloadFile, value.financing),
        workingCapital: from_candid_WorkingCapital_n32(_uploadFile, _downloadFile, value.workingCapital),
        cashRequirement: from_candid_CashRequirement_n24(_uploadFile, _downloadFile, value.cashRequirement),
        monthlyOperatingCost: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.monthlyOperatingCost),
        amortization: from_candid_Amortization_n13(_uploadFile, _downloadFile, value.amortization)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moratoriumMonths: bigint;
    explanation: string;
    repaymentStartMonth: bigint;
    interestAccruedDuringMoratorium: _Estimate;
}): {
    moratoriumMonths: bigint;
    explanation: string;
    repaymentStartMonth: bigint;
    interestAccruedDuringMoratorium: Estimate;
} {
    return {
        moratoriumMonths: value.moratoriumMonths,
        explanation: value.explanation,
        repaymentStartMonth: value.repaymentStartMonth,
        interestAccruedDuringMoratorium: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.interestAccruedDuringMoratorium)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loanAmount: _Estimate;
    scheme: _SchemeRule;
    feasibleProjectCost: _Estimate;
    beneficiaryContribution: _Estimate;
    maximumLoan: _Estimate;
}): {
    loanAmount: Estimate;
    scheme: SchemeRule;
    feasibleProjectCost: Estimate;
    beneficiaryContribution: Estimate;
    maximumLoan: Estimate;
} {
    return {
        loanAmount: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.loanAmount),
        scheme: value.scheme,
        feasibleProjectCost: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.feasibleProjectCost),
        beneficiaryContribution: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.beneficiaryContribution),
        maximumLoan: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.maximumLoan)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    initialRequirement: _Estimate;
    emergencyBuffer: _Estimate;
    totalRequirement: _Estimate;
    monthlyRequirement: _Estimate;
}): {
    initialRequirement: Estimate;
    emergencyBuffer: Estimate;
    totalRequirement: Estimate;
    monthlyRequirement: Estimate;
} {
    return {
        initialRequirement: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.initialRequirement),
        emergencyBuffer: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.emergencyBuffer),
        totalRequirement: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.totalRequirement),
        monthlyRequirement: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.monthlyRequirement)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n36(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n40(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    result: _AnalysisResult;
    createdAt: bigint;
    radius: _Radius;
    input: _AnalysisInput;
}): {
    id: bigint;
    result: AnalysisResult;
    createdAt: bigint;
    radius: Radius;
    input: AnalysisInput;
} {
    return {
        id: value.id,
        result: from_candid_AnalysisResult_n45(_uploadFile, _downloadFile, value.result),
        createdAt: value.createdAt,
        radius: from_candid_Radius_n57(_uploadFile, _downloadFile, value.radius),
        input: value.input
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    map: _MapData;
    scores: _Scores;
    risk: _RiskAssessment;
    swot: _SWOT;
    pricing: _Pricing;
    market: _MarketReach;
}): {
    map: MapData;
    scores: Scores;
    risk: RiskAssessment;
    swot: SWOT;
    pricing: Pricing;
    market: MarketReach;
} {
    return {
        map: value.map,
        scores: value.scores,
        risk: from_candid_RiskAssessment_n47(_uploadFile, _downloadFile, value.risk),
        swot: value.swot,
        pricing: from_candid_Pricing_n53(_uploadFile, _downloadFile, value.pricing),
        market: from_candid_MarketReach_n55(_uploadFile, _downloadFile, value.market)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categories: Array<_RiskCategory>;
}): {
    categories: Array<RiskCategory>;
} {
    return {
        categories: from_candid_vec_n49(_uploadFile, _downloadFile, value.categories)
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    why: string;
    whatToDo: string;
    level: _RiskLevel;
    category: string;
}): {
    why: string;
    whatToDo: string;
    level: RiskLevel;
    category: string;
} {
    return {
        why: value.why,
        whatToDo: value.whatToDo,
        level: from_candid_RiskLevel_n52(_uploadFile, _downloadFile, value.level),
        category: value.category
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    packagingCost: _Estimate;
    recommendedPriceRange: {
        max: bigint;
        min: bigint;
    };
    productionCost: _Estimate;
    transportCost: _Estimate;
    competitorPriceRange: {
        avg: bigint;
        max: bigint;
        min: bigint;
    };
    operatingCost: _Estimate;
    estimatedMargin: _Estimate;
}): {
    packagingCost: Estimate;
    recommendedPriceRange: {
        max: bigint;
        min: bigint;
    };
    productionCost: Estimate;
    transportCost: Estimate;
    competitorPriceRange: {
        avg: bigint;
        max: bigint;
        min: bigint;
    };
    operatingCost: Estimate;
    estimatedMargin: Estimate;
} {
    return {
        packagingCost: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.packagingCost),
        recommendedPriceRange: value.recommendedPriceRange,
        productionCost: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.productionCost),
        transportCost: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.transportCost),
        competitorPriceRange: value.competitorPriceRange,
        operatingCost: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.operatingCost),
        estimatedMargin: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.estimatedMargin)
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    demandIndicators: Array<string>;
    potentialCustomerBase: _Estimate;
    competitionLevel: string;
    nearbyMarkets: Array<string>;
    estimatedReach: _Estimate;
    supplyIndicators: Array<string>;
    underservedOpportunities: Array<string>;
    distributionChannels: Array<string>;
    accessibility: string;
}): {
    demandIndicators: Array<string>;
    potentialCustomerBase: Estimate;
    competitionLevel: string;
    nearbyMarkets: Array<string>;
    estimatedReach: Estimate;
    supplyIndicators: Array<string>;
    underservedOpportunities: Array<string>;
    distributionChannels: Array<string>;
    accessibility: string;
} {
    return {
        demandIndicators: value.demandIndicators,
        potentialCustomerBase: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.potentialCustomerBase),
        competitionLevel: value.competitionLevel,
        nearbyMarkets: value.nearbyMarkets,
        estimatedReach: from_candid_Estimate_n15(_uploadFile, _downloadFile, value.estimatedReach),
        supplyIndicators: value.supplyIndicators,
        underservedOpportunities: value.underservedOpportunities,
        distributionChannels: value.distributionChannels,
        accessibility: value.accessibility
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _SchemeStatus;
    documents: Array<string>;
    moratoriumMonths: [] | [bigint];
    projectCostRange: _ProjectCostRange;
    beneficiaryType: string;
    marginRequirement: [] | [bigint];
    name: string;
    eligibility: string;
    tenureMonths: [] | [bigint];
    loanPercentage: [] | [bigint];
    interestRate: [] | [number];
    lastVerifiedDate: _Timestamp;
    officialSource: string;
}): {
    id: bigint;
    status: SchemeStatus;
    documents: Array<string>;
    moratoriumMonths?: bigint;
    projectCostRange: ProjectCostRange;
    beneficiaryType: string;
    marginRequirement?: bigint;
    name: string;
    eligibility: string;
    tenureMonths?: bigint;
    loanPercentage?: bigint;
    interestRate?: number;
    lastVerifiedDate: Timestamp;
    officialSource: string;
} {
    return {
        id: value.id,
        status: from_candid_SchemeStatus_n64(_uploadFile, _downloadFile, value.status),
        documents: value.documents,
        moratoriumMonths: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.moratoriumMonths)),
        projectCostRange: value.projectCostRange,
        beneficiaryType: value.beneficiaryType,
        marginRequirement: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.marginRequirement)),
        name: value.name,
        eligibility: value.eligibility,
        tenureMonths: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.tenureMonths)),
        loanPercentage: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.loanPercentage)),
        interestRate: record_opt_to_undefined(from_candid_opt_n67(_uploadFile, _downloadFile, value.interestRate)),
        lastVerifiedDate: value.lastVerifiedDate,
        officialSource: value.officialSource
    };
}
function from_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heading: string;
    matches: Array<_SchemeMatch>;
}): {
    heading: string;
    matches: Array<SchemeMatch>;
} {
    return {
        heading: value.heading,
        matches: from_candid_vec_n72(_uploadFile, _downloadFile, value.matches)
    };
}
function from_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moratoriumMonths: [] | [bigint];
    requiredDocuments: Array<string>;
    scheme: _Scheme;
    loan: [] | [bigint];
    officialVerificationNote: string;
    tenureMonths: [] | [bigint];
    interestRate: [] | [number];
    projectCostLimit: _ProjectCostRange;
    contribution: [] | [bigint];
    whyMayFit: string;
}): {
    moratoriumMonths?: bigint;
    requiredDocuments: Array<string>;
    scheme: Scheme;
    loan?: bigint;
    officialVerificationNote: string;
    tenureMonths?: bigint;
    interestRate?: number;
    projectCostLimit: ProjectCostRange;
    contribution?: bigint;
    whyMayFit: string;
} {
    return {
        moratoriumMonths: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.moratoriumMonths)),
        requiredDocuments: value.requiredDocuments,
        scheme: from_candid_Scheme_n62(_uploadFile, _downloadFile, value.scheme),
        loan: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.loan)),
        officialVerificationNote: value.officialVerificationNote,
        tenureMonths: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.tenureMonths)),
        interestRate: record_opt_to_undefined(from_candid_opt_n67(_uploadFile, _downloadFile, value.interestRate)),
        projectCostLimit: value.projectCostLimit,
        contribution: record_opt_to_undefined(from_candid_opt_n66(_uploadFile, _downloadFile, value.contribution)),
        whyMayFit: value.whyMayFit
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Estimated: null;
} | {
    UserProvided: null;
} | {
    Calculated: null;
} | {
    Observed: null;
}): Provenance {
    return "Estimated" in value ? Provenance.Estimated : "UserProvided" in value ? Provenance.UserProvided : "Calculated" in value ? Provenance.Calculated : "Observed" in value ? Provenance.Observed : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): Confidence {
    return "Low" in value ? Confidence.Low : "High" in value ? Confidence.High : "Medium" in value ? Confidence.Medium : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    R5km: null;
} | {
    R10km: null;
}): Radius {
    return "R5km" in value ? Radius.R5km : "R10km" in value ? Radius.R10km : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UnderReview: null;
} | {
    Inactive: null;
} | {
    Active: null;
}): SchemeStatus {
    return "UnderReview" in value ? SchemeStatus.UnderReview : "Inactive" in value ? SchemeStatus.Inactive : "Active" in value ? SchemeStatus.Active : value;
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RiskCategory>): Array<RiskCategory> {
    return value.map((x)=>from_candid_RiskCategory_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Analysis>): Array<Analysis> {
    return value.map((x)=>from_candid_Analysis_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Scheme>): Array<Scheme> {
    return value.map((x)=>from_candid_Scheme_n62(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SchemeMatch>): Array<SchemeMatch> {
    return value.map((x)=>from_candid_SchemeMatch_n73(_uploadFile, _downloadFile, x));
}
function to_candid_ChatMessage_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatMessage): _ChatMessage {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ChatRequest_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRequest): _ChatRequest {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Radius_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Radius): _Radius {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    role: Variant_user_assistant;
}): {
    content: string;
    role: {
        user: null;
    } | {
        assistant: null;
    };
} {
    return {
        content: value.content,
        role: to_candid_variant_n12(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    history: Array<ChatMessage>;
    analysisId: bigint;
    message: string;
}): {
    history: Array<_ChatMessage>;
    analysisId: bigint;
    message: string;
} {
    return {
        history: to_candid_vec_n9(_uploadFile, _downloadFile, value.history),
        analysisId: value.analysisId,
        message: value.message
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_user_assistant): {
    user: null;
} | {
    assistant: null;
} {
    return value == Variant_user_assistant.user ? {
        user: null
    } : value == Variant_user_assistant.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Radius): {
    R5km: null;
} | {
    R10km: null;
} {
    return value == Radius.R5km ? {
        R5km: null
    } : value == Radius.R10km ? {
        R10km: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ChatMessage>): Array<_ChatMessage> {
    return value.map((x)=>to_candid_ChatMessage_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
